# Source: standard parameter values of sb3 DQN

policy: MlpPolicy
learning_rate: !!float 1e-4
batch_size: 32
buffer_size: 1_000_000
learning_starts: 50000
gamma: 0.99
target_update_interval: 600
train_freq: 4
gradient_steps: 8
exploration_fraction: 0.2
exploration_final_eps: 0.07
# policy_kwargs: "dict(net_arch=[256, 256])"